# Synthetic Arrow fixture; no reference genome or MACS required.
suppressPackageStartupMessages(library(ArchR))
repo <- normalizePath('.')
source(file.path(repo, 'wf/R/complete_archr.R'))
exprs <- parse(file.path(repo, 'wf/R/archr.R'))
for(e in exprs) if(is.call(e) && identical(e[[1]],as.name('<-')) && as.character(e[[2]]) %in% c('rebase_group_coverage_paths','rebase_saved_archr_project')) eval(e)
root <- tempfile('archr-roundtrip-'); dir.create(root); setwd(root)
pdir <- file.path(root,'project'); dir.create(pdir); dir.create(file.path(pdir,'ArrowFiles')); dir.create(file.path(pdir,'Annotations'))
ns <- asNamespace('ArchR'); init <- get('.initializeMat',ns); add <- get('.addMatToArrow',ns)
features <- data.frame(seqnames='chr1',idx=1L,start=1L,end=10L,name='gene1')
motifs <- data.frame(seqnames=c('deviations','z'),idx=c(1L,1L),name=c('TF1','TF1'))
arrows <- setNames(file.path(pdir,'ArrowFiles',c('s1.arrow','s2.arrow')),c('s1','s2'))
for(s in names(arrows)) {
 f <- arrows[[s]]; h5createFile(f); h5write('Arrow',f,'Class'); h5createGroup(f,'Metadata'); h5write(s,f,'Metadata/Sample'); h5write(c('c1','c2'),f,'Metadata/CellNames'); h5write(c(10L,20L),f,'Metadata/nFrags')
 for(g in c('GeneScoreMatrix','PeakMatrix','MotifMatrix')) {
  init(f,Group=g,Class=if(g=='MotifMatrix') 'Assays' else 'Double',cellNames=paste0(s,'#',c('c1','c2')),params='test',featureDF=if(g=='MotifMatrix') motifs else features)
  for(seq in if(g=='MotifMatrix') c('deviations','z') else 'chr1') add(mat=as(Matrix(matrix(c(1,2),nrow=1,dimnames=list(NULL,paste0(s,"#",c("c1","c2")))),sparse=TRUE),'dgCMatrix'),ArrowFile=f,Group=paste0(g,'/',seq))
 }
 h5write('Finished',f,'MotifMatrix/Info/Completed')
}
p <- new('ArchRProject'); p@projectMetadata <- SimpleList(outputDirectory=pdir)
p@sampleColData <- DataFrame(ArrowFiles=arrows,row.names=names(arrows))
p@cellColData <- DataFrame(Sample=rep(names(arrows),each=2),nFrags=rep(c(10L,20L),2),TSSEnrichment=rep(2,4),row.names=paste0(rep(names(arrows),each=2),'#',c('c1','c2')))
p@peakSet <- GRanges('chr1',IRanges(1,10)); p@peakSet$idx <- 1L
matches <- SummarizedExperiment(assays=SimpleList(matches=matrix(TRUE,nrow=1,dimnames=list(NULL,'TF1'))),rowRanges=p@peakSet)
mp <- file.path(pdir,'Annotations','matches.rds'); saveRDS(matches,mp)
p@peakAnnotation <- SimpleList(Motif=SimpleList(Name='Motif',Matches=mp))
dir.create(file.path(pdir, 'ImputeWeights'))
weight_path <- file.path(pdir, 'ImputeWeights', 'weights.rds')
saveRDS(matrix(1), weight_path)
p@imputeWeights <- SimpleList(list(Weights = list(weight_path)))
validate_complete_archr_project(p)
save_complete_archr_project(p,file.path(root,'saved'))
saved <- ArchR::loadArchRProject(file.path(root, 'saved'), force = FALSE, showLogo = FALSE)
stopifnot(file.exists(saved@imputeWeights$Weights[[1]]))
stopifnot(startsWith(saved@imputeWeights$Weights[[1]], normalizePath(file.path(root, 'saved'))))
stopifnot(identical(readRDS(saved@imputeWeights$Weights[[1]]), matrix(1)))
cat('Complete project matrix read, weight preservation and save/reload passed\n')
setwd(repo)
unlink(root,recursive=TRUE)
